
export const FETCH_WORKOUTS = 'FETCH_WORKOUTS'
export const FETCH_WORKOUTS_SUCCESS = 'FETCH_WORKOUTS_SUCCESS'
export const FETCH_WORKOUTS_ERROR = 'FETCH_WORKOUTS_ERROR'

export const ADD_WORKOUT = 'ADD_WORKOUT'
export const DELETE_WORKOUT = 'DELETE_WORKOUT'
export const EDIT_WORKOUT = 'EDIT_WORKOUT'

export const SET_WORKOUT = 'SET_WORKOUT'
export const ADD_WORKOUT_EXERCISE = 'ADD_WORKOUT_EXERCISE'
export const REMOVE_WORKOUT_EXERCISE = 'REMOVE_WORKOUT_EXERCISE'

export const FETCH_EXERCISES = 'FETCH_EXERCISES'
export const FETCH_EXERCISES_SUCCESS = 'FETCH_EXERCISES_SUCCESS'
export const FETCH_EXERCISES_ERROR = 'FETCH_EXERCISES_ERRROR'

export const ADD_EXERCISE = 'ADD_EXERCISE'
export const DELETE_EXERCISE = 'DELETE_EXERCISE'
export const EDIT_EXERCISE = 'EDIT_EXERCISE'