export const FETCH_USER = 'FETCH_USER'

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'

export const REGISTER_USER = 'REGISTER_USER'