export const LOAD_NUTRITION = 'LOAD_NUTRITION'
export const LOAD_NUTRITION_ERROR = 'LOAD_NUTRITION_ERROR'
export const LOAD_NUTRITION_SUCCESS = 'LOAD_NUTRITION_SUCCESS'

export const SEARCH_NUTRITION = 'SEARCH_NUTRITION'
export const SEARCH_NUTRITION_ERROR = 'SEARCH_NUTRITION_ERROR'
export const SEARCH_NUTRITION_SUCCESS = 'SEARCH_NUTRITION_SUCCESS'

export const GET_RECENT_NUTRITION = 'GET_RECENT_NUTRITION'
export const GET_RECENT_NUTRITION_ERROR = 'GET_RECENT_NUTRITION_ERROR'
export const GET_RECENT_NUTRITION_SUCCESS = 'GET_RECENT_NUTRITION_SUCCESS'

export const REFRESH_NUTRITION = 'REFRESH_NUTRITION'
export const REFRESH_NUTRITION_SUCCESS = 'REFRESH_NUTRITION_SUCCESS'

export const ADD_NUTRITION_ITEM = 'ADD_NUTRITION_ITEM'
export const EDIT_NUTRITION_ITEM =  'EDIT_NUTRITION_ITEM'
export const DELETE_NUTRITION_ITEM = 'DELETE_NUTRITION_ITEM'

export const SET_FILTER_VALUE = 'SET_FILTER_VALUE'
