export const LOAD_NUTRITION = 'LOAD_NUTRITION'
export const LOAD_NUTRITION_ERROR = 'LOAD_NUTRITION_ERROR'
export const LOAD_NUTRITION_SUCCESS = 'LOAD_NUTRITION_SUCCESS'

export const REFRESH_NUTRITION = 'REFRESH_NUTRITION'

export const ADD_NUTRITION_ITEM = 'ADD_NUTRITION_ITEM'
export const EDIT_NUTRITION_ITEM =  'EDIT_NUTRITION_ITEM'
export const DELETE_NUTRITION_ITEM = 'DELETE_NUTRITION_ITEM'

export const SET_FILTERED_ITEMS = 'SET_FILTERED_ITEMS'
