export const LOAD_SEARCH_ENTRIES = 'LOAD_SEARCH_ENTRIES'
export const RESET_SEARCH_ENTRIES = 'RESET_SEARCH_ENTRIES'
export const SEARCH_ENTRIES = 'SEARCH_ENTRIES' 

export const ADD_ITEM_TO_ENTRY = 'ADD_ITEM_TO_ENTRY'
export const REMOVE_ITEM_FROM_ENTRY = 'REMOVE_ITEM_FROM_ENTRY'
export const LOAD_NUTRITION_ENTRIES = 'LOAD_NUTRITION_ENTRIES'
export const RESET_ENTRIES = 'RESET_ENTRIES'