
export const FETCH_CARDS = 'FETCH_CARDS'
export const GET_CARDS = 'GET_CARDS'
export const REGISTER_CARDS = 'REGISTER_CARDS'
export const TOGGLE_STATUS = 'TOGGLE_STATUS'

export const ENTER_EDIT_MODE = 'ENTER_EDIT_MODE'
export const EXIT_EDIT_MODE = 'EXIT_EDIT_MODE'  
